apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opentelemetry-operator-system

helmCharts:
- name: opentelemetry-operator
  includeCRDs: true
  releaseName: opentelemetry-operator
  namespace: opentelemetry-operator-system
  version: 0.90.2
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  valuesInline:
    admissionWebhooks:
      certManager:
        enabled: true
    admissionWebhooks:
      autoGenerateCert:
        enabled: false
    manager:
      createRbacPermissions: true

resources:
- jaeger.yaml
